OOP課題1
YaKumagai/php_exercise_oop pull request #1
Opened 2021-02-14 10:53 UTC by YaKumagai

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise_org/01_oop/01.md

### メッセージ
確認お願いします。

2021-02-14 12:23 UTC, kazu-taka requested changes
@YaKumagai 
コメントしましたので、修正お願いします🙏

2021-02-14 12:23 UTC, kazu-taka commented on index.php
> +    public $getColor;
@YaKumagai 
オブジェクト指向3でも学習しましたが、プロパティは基本的にprivateで作成します！
publicで作成してしまうと、誰でもプロパティを変更出来てしまうからです。
https://github.com/elites-team/2months_course/blob/master/doc/06_php/study02/01_oop/03.md
ですので、まずはpublicで宣言しているプロパティを全てprivateに変更して下さい。
また、プロパティは、$nameや$numberとして、そのプロパティの値を返すインタンスメソッド(getNameやgetNumber)を作成して下さい😊

2021-02-14 12:23 UTC, kazu-taka commented on index.php
> +$car->selfIntroduction();
@YaKumagai 
こちらの部分が、課題に記載してある内容から変更されてしまっているので、以下の内容に修正して下さい✨
```php
$car1 = new Car('ランクル', 100, 'black');

// 車名(車種)を取得
echo $car1->getName();
echo '<br>';

// 車体番号を取得
echo $car1->getNumber();
echo '<br>';

// カラーを取得
echo $car1->getColor();
echo '<br>';

// 車の情報表示を表示
echo $car1->information();
echo '<br>';

// 車名(車種)を更新
$car1->setName('アルファード');
echo $car1->getName();
echo '<br>';

// 車体番号を取得
$car1->setNumber(200);
echo $car1->getNumber();
echo '<br>';

// カラーを取得
$car1->setColor('red');
echo $car1->getColor();
echo '<br>';

// 車の情報表示を表示
echo $car1->information();
echo '<br>';
```
上記のコードを実行した時に、課題と同じ結果が表示されるように、Carクラスの修正をお願いします:bow:
(selfIntroductionメソッドも修正が入ります)

2021-02-15 08:11 UTC, YaKumagai commented on index.php
> +$car->selfIntroduction();
```private $xName```と```$this->xName```は、同じで、```$Name```とは、違うことがわかりずらく、このようにしました。
申し訳ありません。
必要であれば、直します。🙇

2021-02-15 08:59 UTC, yukishimizumg commented
OKです！マージしてください✨
![LGTM](https://image.lgtmoon.dev/116434)

2021-02-15 11:29 UTC, merged